// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchedulerWpfApp.Data;

#nullable disable

namespace SchedulerWpfApp.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250612062400_UpdateDatabase")]
    partial class UpdateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("SchedulerWpfApp.Model.Curriculum", b =>
                {
                    b.Property<string>("CurriculumCode")
                        .HasColumnType("TEXT")
                        .HasColumnName("CurriculumCode");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IsActive");

                    b.HasKey("CurriculumCode");

                    b.ToTable("Curriculum");
                });

            modelBuilder.Entity("SchedulerWpfApp.Model.CurriculumSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<int>("Credit")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Credit");

                    b.Property<string>("CurriculumCode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("CurriculumCode");

                    b.Property<bool>("IsCombo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IsCombo");

                    b.Property<string>("SubjectCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("SubjectCode");

                    b.Property<string>("SubjectNameEnglish")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("SubjectNameEnglish");

                    b.Property<string>("SubjectNameVietnamese")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("SubjectNameVietnamese");

                    b.Property<int>("TermNo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TermNo");

                    b.Property<int?>("TotalSlots")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TotalSLots");

                    b.HasKey("Id");

                    b.HasIndex("SubjectCode");

                    b.HasIndex("CurriculumCode", "SubjectCode")
                        .HasDatabaseName("IX_CurriculumCode_SubjectCode");

                    b.ToTable("CurriculumSubject");
                });

            modelBuilder.Entity("SchedulerWpfApp.Model.GroupClass", b =>
                {
                    b.Property<string>("GroupName")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurriculumCode")
                        .HasColumnType("TEXT")
                        .HasColumnName("CurriculumCode");

                    b.Property<string>("Department")
                        .HasColumnType("TEXT")
                        .HasColumnName("Department");

                    b.Property<string>("Major")
                        .HasColumnType("TEXT")
                        .HasColumnName("Major");

                    b.Property<string>("Term")
                        .HasColumnType("TEXT")
                        .HasColumnName("Term");

                    b.HasKey("GroupName");

                    b.HasIndex("CurriculumCode")
                        .HasDatabaseName("IX_CurriculumCode");

                    b.ToTable("GroupClass");
                });

            modelBuilder.Entity("SchedulerWpfApp.Model.Lecturer", b =>
                {
                    b.Property<string>("LecturerId")
                        .HasColumnType("TEXT")
                        .HasColumnName("LecturerId");

                    b.Property<string>("Department")
                        .HasColumnType("TEXT")
                        .HasColumnName("Department");

                    b.Property<string>("LecturerName")
                        .HasColumnType("TEXT")
                        .HasColumnName("LecturerName");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT")
                        .HasColumnName("Role");

                    b.HasKey("LecturerId");

                    b.ToTable("Lecturer");
                });

            modelBuilder.Entity("SchedulerWpfApp.Model.LecturerRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DayName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("DayName");

                    b.Property<bool>("DistanceNote")
                        .HasColumnType("INTEGER")
                        .HasColumnName("DistanceNote ");

                    b.Property<bool>("HasHealthIssue")
                        .HasColumnType("INTEGER")
                        .HasColumnName("HasHealthIssue");

                    b.Property<string>("LecturerId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("LecturerId");

                    b.Property<string>("Session")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Session");

                    b.Property<string>("SlotTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("SlotTime");

                    b.Property<string>("SlotType")
                        .HasColumnType("TEXT")
                        .HasColumnName("SlotType");

                    b.HasKey("Id");

                    b.HasIndex("LecturerId");

                    b.ToTable("LecturerRequests");
                });

            modelBuilder.Entity("SchedulerWpfApp.Model.LecturerSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LecturerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LecturerName")
                        .HasColumnType("TEXT")
                        .HasColumnName("LecturerName");

                    b.Property<string>("Major")
                        .HasColumnType("TEXT")
                        .HasColumnName("Major");

                    b.Property<int?>("NumberOfClasses")
                        .HasColumnType("INTEGER")
                        .HasColumnName("NumberOfClasses");

                    b.Property<string>("SubjectCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectName")
                        .HasColumnType("TEXT")
                        .HasColumnName("SubjectName");

                    b.Property<string>("Term")
                        .HasColumnType("TEXT")
                        .HasColumnName("Term");

                    b.Property<int?>("TotalSlots")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TotalSLots");

                    b.HasKey("Id");

                    b.HasIndex("SubjectCode");

                    b.HasIndex("LecturerId", "SubjectCode")
                        .HasDatabaseName("IX_LecturerId_SubjectCode");

                    b.ToTable("LecturerSubject");
                });

            modelBuilder.Entity("SchedulerWpfApp.Model.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT")
                        .HasColumnName("Email");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT")
                        .HasColumnName("FirstName");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT")
                        .HasColumnName("LastName");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT")
                        .HasColumnName("Phone");

                    b.HasKey("Id");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("SchedulerWpfApp.Model.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("RoomId");

                    b.Property<string>("Building")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Building");

                    b.Property<int>("Floor")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Floor");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("RoomName");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Status");

                    b.Property<int>("TotalPersons")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TotalPersons");

                    b.Property<string>("TypeOfRoom")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("TypeOfRoom");

                    b.HasKey("RoomId");

                    b.HasIndex("RoomName")
                        .HasDatabaseName("IX_RoomName");

                    b.ToTable("Room");
                });

            modelBuilder.Entity("SchedulerWpfApp.Model.Schedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("Date");

                    b.Property<string>("GroupName")
                        .HasColumnType("TEXT")
                        .HasColumnName("GroupName");

                    b.Property<string>("LecturerId")
                        .HasColumnType("TEXT")
                        .HasColumnName("LecturerId");

                    b.Property<string>("Major")
                        .HasColumnType("TEXT")
                        .HasColumnName("Major");

                    b.Property<string>("PartOfDay")
                        .HasColumnType("TEXT")
                        .HasColumnName("PartOfDay");

                    b.Property<int?>("RoomId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("RoomNo");

                    b.Property<int?>("SessionNo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SessionNo");

                    b.Property<string>("SlotTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("SlotTime");

                    b.Property<string>("SlotTypeCode")
                        .HasColumnType("TEXT")
                        .HasColumnName("SlotTypeCode");

                    b.Property<string>("StatusSlot")
                        .HasColumnType("TEXT")
                        .HasColumnName("StatusSlot");

                    b.Property<string>("SubjectCode")
                        .HasColumnType("TEXT")
                        .HasColumnName("SubjectCode");

                    b.Property<string>("TypeSlot")
                        .HasColumnType("TEXT")
                        .HasColumnName("TypeSlot");

                    b.HasKey("ScheduleId");

                    b.HasIndex("GroupName");

                    b.HasIndex("LecturerId");

                    b.HasIndex("RoomId");

                    b.HasIndex("SubjectCode");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("SchedulerWpfApp.Model.Subject", b =>
                {
                    b.Property<string>("SubjectCode")
                        .HasColumnType("TEXT")
                        .HasColumnName("SubjectCode");

                    b.Property<string>("SubjectNameEnglish")
                        .HasColumnType("TEXT")
                        .HasColumnName("SubjectName");

                    b.Property<string>("SubjectNameVietnamese")
                        .HasColumnType("TEXT")
                        .HasColumnName("SubjectNameVietnamese");

                    b.Property<int>("TotalCredits")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TotalCredits");

                    b.Property<int>("TotalTime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TotalTime");

                    b.HasKey("SubjectCode");

                    b.ToTable("Subject");
                });

            modelBuilder.Entity("SchedulerWpfApp.Model.CurriculumSubject", b =>
                {
                    b.HasOne("SchedulerWpfApp.Model.Curriculum", "Curriculum")
                        .WithMany("CurriculumSubjects")
                        .HasForeignKey("CurriculumCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchedulerWpfApp.Model.Subject", "Subject")
                        .WithMany("CurriculumSubjects")
                        .HasForeignKey("SubjectCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Curriculum");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("SchedulerWpfApp.Model.LecturerRequest", b =>
                {
                    b.HasOne("SchedulerWpfApp.Model.Lecturer", "Lecturer")
                        .WithMany("LecturerRequests")
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lecturer");
                });

            modelBuilder.Entity("SchedulerWpfApp.Model.LecturerSubject", b =>
                {
                    b.HasOne("SchedulerWpfApp.Model.Lecturer", "Lecturer")
                        .WithMany("LecturerSubjects")
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchedulerWpfApp.Model.Subject", "Subject")
                        .WithMany("LecturerSubjects")
                        .HasForeignKey("SubjectCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lecturer");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("SchedulerWpfApp.Model.Schedule", b =>
                {
                    b.HasOne("SchedulerWpfApp.Model.GroupClass", "GroupClass")
                        .WithMany("Schedules")
                        .HasForeignKey("GroupName")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SchedulerWpfApp.Model.Lecturer", "Lecturer")
                        .WithMany("Schedules")
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SchedulerWpfApp.Model.Room", "Room")
                        .WithMany("Schedules")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SchedulerWpfApp.Model.Subject", "Subject")
                        .WithMany("Schedules")
                        .HasForeignKey("SubjectCode")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("GroupClass");

                    b.Navigation("Lecturer");

                    b.Navigation("Room");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("SchedulerWpfApp.Model.Curriculum", b =>
                {
                    b.Navigation("CurriculumSubjects");
                });

            modelBuilder.Entity("SchedulerWpfApp.Model.GroupClass", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("SchedulerWpfApp.Model.Lecturer", b =>
                {
                    b.Navigation("LecturerRequests");

                    b.Navigation("LecturerSubjects");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("SchedulerWpfApp.Model.Room", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("SchedulerWpfApp.Model.Subject", b =>
                {
                    b.Navigation("CurriculumSubjects");

                    b.Navigation("LecturerSubjects");

                    b.Navigation("Schedules");
                });
#pragma warning restore 612, 618
        }
    }
}
