// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchedulerWpfApp.Data;

#nullable disable

namespace SchedulerWpfApp.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250515065923_AddGroupNamTable")]
    partial class AddGroupNamTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("SchedulerWpfApp.Model.GroupName", b =>
                {
                    b.Property<string>("ClassId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT")
                        .HasColumnName("Category");

                    b.Property<string>("Major")
                        .HasColumnType("TEXT")
                        .HasColumnName("Major");

                    b.Property<int>("NumberOfScheduler")
                        .HasColumnType("INTEGER")
                        .HasColumnName("NumberOfScheduler");

                    b.Property<int>("NumberOfStudents")
                        .HasColumnType("INTEGER")
                        .HasColumnName("NumberOfStudents");

                    b.HasKey("ClassId");

                    b.ToTable("GroupName");

                    b.HasData(
                        new
                        {
                            ClassId = "CL01",
                            Category = "Class room",
                            Major = "SE",
                            NumberOfScheduler = 5,
                            NumberOfStudents = 35
                        },
                        new
                        {
                            ClassId = "CL02",
                            Category = "Class room",
                            Major = "MC",
                            NumberOfScheduler = 5,
                            NumberOfStudents = 35
                        },
                        new
                        {
                            ClassId = "CL03",
                            Category = "Computer lab",
                            Major = "SE",
                            NumberOfScheduler = 5,
                            NumberOfStudents = 35
                        });
                });

            modelBuilder.Entity("SchedulerWpfApp.Model.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT")
                        .HasColumnName("Email");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT")
                        .HasColumnName("FirstName");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT")
                        .HasColumnName("LastName");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT")
                        .HasColumnName("Phone");

                    b.HasKey("Id");

                    b.ToTable("Person");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            LastName = "Doe",
                            Phone = "123-456-7890"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Jane.smith@example.com",
                            FirstName = "Jane",
                            LastName = "Smith",
                            Phone = "987-654-3210"
                        },
                        new
                        {
                            Id = 3,
                            Email = "Alice.johnson@example.com",
                            FirstName = "Alice",
                            LastName = "Johnson",
                            Phone = "555-123-4567"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
