// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchedulerWpfApp.Data;

#nullable disable

namespace SchedulerWpfApp.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250523064414_AddSchedulesTable")]
    partial class AddSchedulesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("SchedulerWpfApp.Model.GroupName", b =>
                {
                    b.Property<string>("ClassId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT")
                        .HasColumnName("Category");

                    b.Property<string>("Major")
                        .HasColumnType("TEXT")
                        .HasColumnName("Major");

                    b.Property<int>("NumberOfScheduler")
                        .HasColumnType("INTEGER")
                        .HasColumnName("NumberOfScheduler");

                    b.Property<int>("NumberOfStudents")
                        .HasColumnType("INTEGER")
                        .HasColumnName("NumberOfStudents");

                    b.HasKey("ClassId");

                    b.ToTable("GroupName");

                    b.HasData(
                        new
                        {
                            ClassId = "CL01",
                            Category = "Class room",
                            Major = "SE",
                            NumberOfScheduler = 5,
                            NumberOfStudents = 35
                        },
                        new
                        {
                            ClassId = "CL02",
                            Category = "Class room",
                            Major = "MC",
                            NumberOfScheduler = 5,
                            NumberOfStudents = 35
                        },
                        new
                        {
                            ClassId = "CL03",
                            Category = "Computer lab",
                            Major = "SE",
                            NumberOfScheduler = 5,
                            NumberOfStudents = 35
                        });
                });

            modelBuilder.Entity("SchedulerWpfApp.Model.Lecturer", b =>
                {
                    b.Property<string>("LecturerId")
                        .HasColumnType("TEXT")
                        .HasColumnName("LecturerId");

                    b.Property<string>("LecturerName")
                        .HasColumnType("TEXT")
                        .HasColumnName("LecturerName");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT")
                        .HasColumnName("Role");

                    b.HasKey("LecturerId");

                    b.ToTable("Lecturer");

                    b.HasData(
                        new
                        {
                            LecturerId = "1",
                            LecturerName = "Nguyễn Văn A"
                        },
                        new
                        {
                            LecturerId = "2",
                            LecturerName = "Trần Thị B"
                        },
                        new
                        {
                            LecturerId = "L1",
                            LecturerName = "Nguyen Van Xoai"
                        },
                        new
                        {
                            LecturerId = "L2",
                            LecturerName = "Sờ Mai"
                        },
                        new
                        {
                            LecturerId = "L3",
                            LecturerName = "Nguyen Mang Gồ"
                        },
                        new
                        {
                            LecturerId = "L4",
                            LecturerName = "Nguyen Vỉa Hè"
                        },
                        new
                        {
                            LecturerId = "L5",
                            LecturerName = "Nguyen Hoa Hong"
                        },
                        new
                        {
                            LecturerId = "L6",
                            LecturerName = "Nguyen Thi Hoa"
                        },
                        new
                        {
                            LecturerId = "L7",
                            LecturerName = "Nguyen Thi Bưởi"
                        },
                        new
                        {
                            LecturerId = "L8",
                            LecturerName = "Nguyen Thi Đào"
                        },
                        new
                        {
                            LecturerId = "L9",
                            LecturerName = "Nguyen Thi Oi"
                        },
                        new
                        {
                            LecturerId = "L10",
                            LecturerName = "Nguyen Thi Cam"
                        },
                        new
                        {
                            LecturerId = "L11",
                            LecturerName = "Nguyen Thi Mit"
                        },
                        new
                        {
                            LecturerId = "L12",
                            LecturerName = "Nguyen Thi Leo"
                        },
                        new
                        {
                            LecturerId = "L13",
                            LecturerName = "Nguyen Thi Man"
                        },
                        new
                        {
                            LecturerId = "L14",
                            LecturerName = "Nguyen Teo Em"
                        },
                        new
                        {
                            LecturerId = "L15",
                            LecturerName = "Nguyen Thi Cam"
                        },
                        new
                        {
                            LecturerId = "L16",
                            LecturerName = "Nguyen Thi Chuoi"
                        },
                        new
                        {
                            LecturerId = "L17",
                            LecturerName = "Nguyen Thi Hoa"
                        });
                });

            modelBuilder.Entity("SchedulerWpfApp.Model.LecturerRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DayName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("DayName");

                    b.Property<string>("LecturerId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("LecturerId");

                    b.Property<string>("Session")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Session");

                    b.Property<string>("SlotTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("SlotTime");

                    b.Property<string>("SlotType")
                        .HasColumnType("TEXT")
                        .HasColumnName("SlotType");

                    b.HasKey("Id");

                    b.ToTable("LecturerRequests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DayName = "Monday",
                            LecturerId = "L1",
                            Session = "A"
                        },
                        new
                        {
                            Id = 2,
                            DayName = "Wednesday",
                            LecturerId = "L1",
                            Session = "A"
                        });
                });

            modelBuilder.Entity("SchedulerWpfApp.Model.LecturerSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LecturerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LecturerName")
                        .HasColumnType("TEXT")
                        .HasColumnName("LecturerName");

                    b.Property<int>("NumberOfClasses")
                        .HasColumnType("INTEGER")
                        .HasColumnName("NumberOfClasses");

                    b.Property<string>("SubjectCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectCode1")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LecturerId");

                    b.HasIndex("SubjectCode1");

                    b.ToTable("LecturerSubject");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LecturerId = "L2",
                            LecturerName = "Sờ Mai",
                            NumberOfClasses = 1,
                            SubjectCode = "SWP391"
                        },
                        new
                        {
                            Id = 2,
                            LecturerId = "L3",
                            LecturerName = "Nguyen Mang Gồ",
                            NumberOfClasses = 1,
                            SubjectCode = "SWP391"
                        },
                        new
                        {
                            Id = 3,
                            LecturerId = "L4",
                            LecturerName = "Nguyen Vỉa Hè",
                            NumberOfClasses = 1,
                            SubjectCode = "SWP391"
                        },
                        new
                        {
                            Id = 4,
                            LecturerId = "L5",
                            LecturerName = "Nguyen Hoa Hong",
                            NumberOfClasses = 1,
                            SubjectCode = "SWT301"
                        },
                        new
                        {
                            Id = 5,
                            LecturerId = "L6",
                            LecturerName = "Nguyen Thi Hoa",
                            NumberOfClasses = 1,
                            SubjectCode = "SWT301"
                        },
                        new
                        {
                            Id = 6,
                            LecturerId = "L7",
                            LecturerName = "Nguyen Thi Bưởi",
                            NumberOfClasses = 1,
                            SubjectCode = "SWT301"
                        },
                        new
                        {
                            Id = 7,
                            LecturerId = "L8",
                            LecturerName = "Nguyen Thi Đào",
                            NumberOfClasses = 1,
                            SubjectCode = "SWT301"
                        },
                        new
                        {
                            Id = 8,
                            LecturerId = "L9",
                            LecturerName = "Nguyen Thi Oi",
                            NumberOfClasses = 1,
                            SubjectCode = "SWR302"
                        },
                        new
                        {
                            Id = 9,
                            LecturerId = "L10",
                            LecturerName = "Nguyen Thi Cam",
                            NumberOfClasses = 1,
                            SubjectCode = "SWR302"
                        },
                        new
                        {
                            Id = 10,
                            LecturerId = "L11",
                            LecturerName = "Nguyen Thi Mit",
                            NumberOfClasses = 1,
                            SubjectCode = "SWR302"
                        },
                        new
                        {
                            Id = 11,
                            LecturerId = "L12",
                            LecturerName = "Nguyen Thi Leo",
                            NumberOfClasses = 1,
                            SubjectCode = "SWR302"
                        },
                        new
                        {
                            Id = 12,
                            LecturerId = "L13",
                            LecturerName = "Nguyen Thi Man",
                            NumberOfClasses = 1,
                            SubjectCode = "PRN211"
                        },
                        new
                        {
                            Id = 13,
                            LecturerId = "L14",
                            LecturerName = "Nguyen Teo Em",
                            NumberOfClasses = 1,
                            SubjectCode = "PRN211"
                        },
                        new
                        {
                            Id = 14,
                            LecturerId = "L15",
                            LecturerName = "Nguyen Thi Cam",
                            NumberOfClasses = 1,
                            SubjectCode = "PRN211"
                        },
                        new
                        {
                            Id = 15,
                            LecturerId = "L16",
                            LecturerName = "Nguyen Thi Chuoi",
                            NumberOfClasses = 1,
                            SubjectCode = "PRN211"
                        },
                        new
                        {
                            Id = 16,
                            LecturerId = "L17",
                            LecturerName = "Nguyen Thi Hoa",
                            NumberOfClasses = 1,
                            SubjectCode = "ENW11"
                        });
                });

            modelBuilder.Entity("SchedulerWpfApp.Model.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT")
                        .HasColumnName("Email");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT")
                        .HasColumnName("FirstName");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT")
                        .HasColumnName("LastName");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT")
                        .HasColumnName("Phone");

                    b.HasKey("Id");

                    b.ToTable("Person");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            LastName = "Doe",
                            Phone = "123-456-7890"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Jane.smith@example.com",
                            FirstName = "Jane",
                            LastName = "Smith",
                            Phone = "987-654-3210"
                        },
                        new
                        {
                            Id = 3,
                            Email = "Alice.johnson@example.com",
                            FirstName = "Alice",
                            LastName = "Johnson",
                            Phone = "555-123-4567"
                        });
                });

            modelBuilder.Entity("SchedulerWpfApp.Model.Schedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("Date");

                    b.Property<string>("GroupName")
                        .HasColumnType("TEXT")
                        .HasColumnName("GroupName");

                    b.Property<string>("LecturerId")
                        .HasColumnType("TEXT")
                        .HasColumnName("LecturerId");

                    b.Property<string>("Major")
                        .HasColumnType("TEXT")
                        .HasColumnName("Major");

                    b.Property<string>("PartOfDay")
                        .HasColumnType("TEXT")
                        .HasColumnName("PartOfDay");

                    b.Property<string>("RoomNo")
                        .HasColumnType("TEXT")
                        .HasColumnName("RoomNo");

                    b.Property<int>("SessionNo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SessionNo");

                    b.Property<string>("SlotTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("SlotTime");

                    b.Property<string>("SlotTypeCode")
                        .HasColumnType("TEXT")
                        .HasColumnName("SlotTypeCode");

                    b.Property<string>("StatusSlot")
                        .HasColumnType("TEXT")
                        .HasColumnName("StatusSlot");

                    b.Property<string>("SubjectCode")
                        .HasColumnType("TEXT")
                        .HasColumnName("SubjectCode");

                    b.Property<string>("TypeSlot")
                        .HasColumnType("TEXT")
                        .HasColumnName("TypeSlot");

                    b.HasKey("ScheduleId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("SchedulerWpfApp.Model.Subject", b =>
                {
                    b.Property<string>("SubjectCode")
                        .HasColumnType("TEXT")
                        .HasColumnName("SubjectCode");

                    b.Property<string>("Major")
                        .HasColumnType("TEXT")
                        .HasColumnName("Major");

                    b.Property<string>("SemesterId")
                        .HasColumnType("TEXT")
                        .HasColumnName("SemesterId");

                    b.Property<int>("SlotsPerWeek")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SlotsPerWeek");

                    b.Property<string>("SubjectName")
                        .HasColumnType("TEXT")
                        .HasColumnName("SubjectName");

                    b.Property<int>("TotalSessions")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TotalSessions");

                    b.HasKey("SubjectCode");

                    b.ToTable("Subject");

                    b.HasData(
                        new
                        {
                            SubjectCode = "WDP201",
                            Major = "SE",
                            SemesterId = "SU25",
                            SlotsPerWeek = 20,
                            SubjectName = "Web development",
                            TotalSessions = 1
                        },
                        new
                        {
                            SubjectCode = "SEP492",
                            Major = "SE",
                            SemesterId = "SU25",
                            SlotsPerWeek = 20,
                            SubjectName = "Do an tot nghiep",
                            TotalSessions = 1
                        },
                        new
                        {
                            SubjectCode = "HCM202",
                            Major = "SE",
                            SemesterId = "SU25",
                            SlotsPerWeek = 20,
                            SubjectName = "Tw tuong Ho Chi Minh",
                            TotalSessions = 1
                        },
                        new
                        {
                            SubjectCode = "SWP391",
                            Major = "SE",
                            SemesterId = "",
                            SlotsPerWeek = 2,
                            SubjectName = "Software Engineering",
                            TotalSessions = 4
                        },
                        new
                        {
                            SubjectCode = "SWT301",
                            Major = "SE",
                            SemesterId = "",
                            SlotsPerWeek = 2,
                            SubjectName = "Software Testing",
                            TotalSessions = 4
                        },
                        new
                        {
                            SubjectCode = "SWR302",
                            Major = "SE",
                            SemesterId = "",
                            SlotsPerWeek = 2,
                            SubjectName = "Software Requirement",
                            TotalSessions = 4
                        },
                        new
                        {
                            SubjectCode = "PRN211",
                            Major = "SE",
                            SemesterId = "",
                            SlotsPerWeek = 2,
                            SubjectName = "Programming",
                            TotalSessions = 4
                        },
                        new
                        {
                            SubjectCode = "ENW11",
                            Major = "SE",
                            SemesterId = "",
                            SlotsPerWeek = 1,
                            SubjectName = "English",
                            TotalSessions = 4
                        });
                });

            modelBuilder.Entity("SchedulerWpfApp.Model.LecturerSubject", b =>
                {
                    b.HasOne("SchedulerWpfApp.Model.Lecturer", "Lecturer")
                        .WithMany("LecturerSubjects")
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchedulerWpfApp.Model.Subject", "Subject")
                        .WithMany("LecturerSubjects")
                        .HasForeignKey("SubjectCode1");

                    b.Navigation("Lecturer");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("SchedulerWpfApp.Model.Lecturer", b =>
                {
                    b.Navigation("LecturerSubjects");
                });

            modelBuilder.Entity("SchedulerWpfApp.Model.Subject", b =>
                {
                    b.Navigation("LecturerSubjects");
                });
#pragma warning restore 612, 618
        }
    }
}
