// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchedulerWpfApp.Data;

#nullable disable

namespace SchedulerWpfApp.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");
            
            modelBuilder.Entity("SchedulerWpfApp.Model.Lecturer", b =>
                {
                    b.Property<string>("LecturerId")
                        .HasColumnType("TEXT")
                        .HasColumnName("LecturerId");

                    b.Property<string>("LecturerName")
                        .HasColumnType("TEXT")
                        .HasColumnName("LecturerName");

                    b.HasKey("LecturerId");

                    b.ToTable("Lecturer");

                    b.HasData(
                        new
                        {
                            LecturerId = "1",
                            LecturerName = "Nguyễn Văn A"
                        },
                        new
                        {
                            LecturerId = "2",
                            LecturerName = "Trần Thị B"
                        });
                });

            modelBuilder.Entity("SchedulerWpfApp.Model.LecturerSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LecturerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LecturerName")
                        .HasColumnType("TEXT")
                        .HasColumnName("LecturerName");

                    b.Property<int>("NumberOfClasses")
                        .HasColumnType("INTEGER")
                        .HasColumnName("NumberOfClasses");

                    b.Property<string>("SubjectCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LecturerId");

                    b.HasIndex("SubjectCode");

                    b.ToTable("LecturerSubject");
                    
                    b.HasData(
                        new
                        {
                            Id = 1,
                            LecturerId = "1",
                            LecturerName = "Nguyễn Văn A",
                            NumberOfClasses = 10,
                            SubjectCode = "SEP492"
                        },
                        new
                        {
                            Id = 2,
                            LecturerId = "2",
                            LecturerName = "Trần Thị B",
                            NumberOfClasses = 5,
                            SubjectCode = "SEP492"
                        });
                 });
                 
            modelBuilder.Entity("SchedulerWpfApp.Model.GroupName", b =>
                {
                    b.Property<string>("ClassId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT")
                        .HasColumnName("Category");

                    b.Property<string>("Major")
                        .HasColumnType("TEXT")
                        .HasColumnName("Major");

                    b.Property<int>("NumberOfScheduler")
                        .HasColumnType("INTEGER")
                        .HasColumnName("NumberOfScheduler");

                    b.Property<int>("NumberOfStudents")
                        .HasColumnType("INTEGER")
                        .HasColumnName("NumberOfStudents");

                    b.HasKey("ClassId");

                    b.ToTable("GroupName");

                    b.HasData(
                        new
                        {
                            ClassId = "CL01",
                            Category = "Class room",
                            Major = "SE",
                            NumberOfScheduler = 5,
                            NumberOfStudents = 35
                        },
                        new
                        {
                            ClassId = "CL02",
                            Category = "Class room",
                            Major = "MC",
                            NumberOfScheduler = 5,
                            NumberOfStudents = 35
                        },
                        new
                        {
                            ClassId = "CL03",
                            Category = "Computer lab",
                            Major = "SE",
                            NumberOfScheduler = 5,
                            NumberOfStudents = 35
                        });
                });

            modelBuilder.Entity("SchedulerWpfApp.Model.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT")
                        .HasColumnName("Email");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT")
                        .HasColumnName("FirstName");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT")
                        .HasColumnName("LastName");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT")
                        .HasColumnName("Phone");

                    b.HasKey("Id");

                    b.ToTable("Person");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            LastName = "Doe",
                            Phone = "123-456-7890"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Jane.smith@example.com",
                            FirstName = "Jane",
                            LastName = "Smith",
                            Phone = "987-654-3210"
                        },
                        new
                        {
                            Id = 3,
                            Email = "Alice.johnson@example.com",
                            FirstName = "Alice",
                            LastName = "Johnson",
                            Phone = "555-123-4567"
                        });
                });

            modelBuilder.Entity("SchedulerWpfApp.Model.Subject", b =>
                {
                    b.Property<string>("SubjectCode")
                        .HasColumnType("TEXT")
                        .HasColumnName("SubjectCode");

                    b.Property<string>("Major")
                        .HasColumnType("TEXT")
                        .HasColumnName("Major");

                    b.Property<string>("SemesterId")
                        .HasColumnType("TEXT")
                        .HasColumnName("SemesterId");

                    b.Property<int>("SlotsPerWeek")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SlotsPerWeek");

                    b.Property<string>("SubjectName")
                        .HasColumnType("TEXT")
                        .HasColumnName("SubjectName");

                    b.Property<int>("TotalSessions")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TotalSessions");

                    b.HasKey("SubjectCode");

                    b.ToTable("Subject");

                    b.HasData(
                        new
                        {
                            SubjectCode = "WDP201",
                            Major = "SE",
                            SemesterId = "SU25",
                            SlotsPerWeek = 20,
                            SubjectName = "Web development",
                            TotalSessions = 1
                        },
                        new
                        {
                            SubjectCode = "SEP492",
                            Major = "SE",
                            SemesterId = "SU25",
                            SlotsPerWeek = 20,
                            SubjectName = "Do an tot nghiep",
                            TotalSessions = 1
                        },
                        new
                        {
                            SubjectCode = "HCM202",
                            Major = "SE",
                            SemesterId = "SU25",
                            SlotsPerWeek = 20,
                            SubjectName = "Tw tuong Ho Chi Minh",
                            TotalSessions = 1
                        });
                });

            modelBuilder.Entity("SchedulerWpfApp.Model.LecturerSubject", b =>
                {
                    b.HasOne("SchedulerWpfApp.Model.Lecturer", "Lecturer")
                        .WithMany("LecturerSubjects")
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchedulerWpfApp.Model.Subject", "Subject")
                        .WithMany("LecturerSubjects")
                        .HasForeignKey("SubjectCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lecturer");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("SchedulerWpfApp.Model.Lecturer", b =>
                {
                    b.Navigation("LecturerSubjects");
                });

            modelBuilder.Entity("SchedulerWpfApp.Model.Subject", b =>
                {
                    b.Navigation("LecturerSubjects");
                });
#pragma warning restore 612, 618
        }
    }
}
